[package]
name = "gear-runtime-interface"
description = "Gear Runtime Interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gear-core.workspace = true
gear-lazy-pages-common.workspace = true
gear-lazy-pages = { workspace = true, optional = true }
gear-sandbox-host = { workspace = true, optional = true }

sp-io.workspace = true
sp-runtime-interface.workspace = true
sp-std.workspace = true
sp-wasm-interface.workspace = true

byteorder.workspace = true
codec = { workspace = true }
log = { workspace = true, optional = true }
diffusers = { version = "0.3.1", optional = true }
data = { version = "0.1.0", optional = true, registry = "hackathon-2024-registry" }
tch = { version = "0.13", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["memoryapi"] }

[features]
default = ["std"]
std = [
	"gear-core/std",
	"gear-lazy-pages",
	"gear-sandbox-host",

	"sp-io/std",
	"sp-std/std",
	"sp-runtime-interface/std",
	"sp-wasm-interface/std",

	"byteorder/std",
	"codec/std",
	"log",
	"diffusers",
	"data",
	"tch",
]
