[package]
name = "gear-runtime-interface"
description = "Gear Runtime Interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gear-core.workspace = true
gear-lazy-pages-common.workspace = true
gear-lazy-pages = { workspace = true, optional = true }
gear-sandbox-host = { workspace = true, optional = true }

sp-io.workspace = true
sp-runtime-interface.workspace = true
sp-std.workspace = true
sp-wasm-interface.workspace = true

byteorder.workspace = true
codec = { workspace = true, features = ["derive"] }
log = { workspace = true, optional = true }

plonky2 = { git = "https://github.com/0xPolygonZero/plonky2.git", rev = "1a08e783da3d3cedcc7ae3dc9c06e018ab90da71", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["memoryapi"] }

[features]
default = ["std"]
std = [
	"gear-core/std",
	"gear-lazy-pages",
	"gear-sandbox-host",

	"sp-io/std",
	"sp-std/std",
	"sp-runtime-interface/std",
	"sp-wasm-interface/std",

	"byteorder/std",
	"codec/std",
	"log",

	"plonky2",
]
