[package]
name = "ethexe-consensus"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethexe-signer.workspace = true
ethexe-processor.workspace = true
ethexe-db.workspace = true

gprimitives = { workspace = true, features = ["codec"] }
gear-core.workspace = true

tokio = { workspace = true, features = ["macros", "sync"] }
anyhow.workspace = true
log.workspace = true
parity-scale-codec.workspace = true
async-trait.workspace = true
rand = { workspace = true, features = ["std", "std_rng"] }
derive_more.workspace = true
futures.workspace = true
void = "1.0.2"
