[package]
name = "pallet-gear-bridge-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://gear-tech.io"
repository = "https://github.com/gear-tech/gear"

[dependencies]
jsonrpsee = { workspace = true, features = ["server", "macros"] }
primitive-types.workspace = true

# Substrate packages
sp-api.workspace = true
sp-blockchain.workspace = true
sp-runtime.workspace = true

# Local packages
pallet-gear-bridge-rpc-runtime-api = { workspace = true, features = ["std"] }
