[package]
name = "demo-waiter"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.wasm-dep-builder.program]
exclude-features = ["std", "wasm-wrapper"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
futures.workspace = true
gstd.workspace = true
gcore.workspace = true
parity-scale-codec.workspace = true

[build-dependencies]
wasm-dep-builder.workspace = true

[dev-dependencies]
gtest.workspace = true
gear-core.workspace = true
demo-waiter = { workspace = true, features = ["debug"] }

[features]
debug = ["gstd/debug"]
wasm-wrapper = []
std = ["parity-scale-codec/std", "wasm-wrapper"]
default = ["std"]
