[package]
name = "migration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["macros"] }
env_logger.workspace = true

frame-support.workspace = true
frame-system.workspace = true
frame-remote-externalities.workspace = true
gear-common = { workspace = true, features = ["std"] }
gear-runtime = { workspace = true, features = ["std", "try-runtime"] }
pallet-gear-program = { workspace = true, features = ["std"] }

demo-backend-error.workspace = true
