[package]
name = "demo-constructor-io"
version = "0.1.0"
edition = "2021"

[dependencies]
gcore.workspace = true
parity-scale-codec.workspace = true
gstd = { workspace = true }

[features]
debug = ["gstd/debug"]
wasm-wrapper = []
