[package]
name = "migration-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["macros"] }
log.workspace = true

frame-support.workspace = true
frame-remote-externalities.workspace = true

gear-runtime = { workspace = true, features = ["std", "try-runtime"] }

[dev-dependencies]
env_logger.workspace = true

pallet-gear-program = { workspace = true, features = ["std"] }
