[package]
name = "pallet-gear-binaries"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-dep-builder.builder]
include = ["demo-*", "test-syscalls"]

[dependencies]
demo-async.workspace = true
demo-async-init.workspace = true
demo-async-recursion.workspace = true
demo-async-tester.workspace = true
demo-delayed-sender.workspace = true
demo-distributor.workspace = true
demo-init-fail-sender.workspace = true
demo-init-wait.workspace = true
demo-init-wait-reply-exit.workspace = true
demo-futures-unordered.workspace = true
demo-program-factory.workspace = true
demo-program-generator.workspace = true
demo-proxy.workspace = true
demo-proxy-relay.workspace = true
demo-proxy-reservation-with-gas.workspace = true
demo-read-big-state.workspace = true
demo-incomplete-async-payloads.workspace = true
demo-gas-burned.workspace = true
demo-waiting-proxy.workspace = true
demo-calc-hash-over-blocks.workspace = true
demo-calc-hash-in-one-block.workspace = true
demo-compose.workspace = true
demo-constructor.workspace = true
demo-mul-by-const.workspace = true
demo-wait.workspace = true
demo-waiter.workspace = true
demo-wait-timeout.workspace = true
demo-wait-wake.workspace = true
demo-reserve-gas.workspace = true
demo-rwlock.workspace = true
demo-reservation-manager.workspace = true
demo-send-from-reservation.workspace = true
demo-signal-entry.workspace = true
demo-state-rollback.workspace = true
demo-async-signal-entry.workspace = true
demo-async-custom-entry.workspace = true
demo-out-of-memory.workspace = true
demo-ping.workspace = true
demo-sync-duplicate.workspace = true
demo-custom.workspace = true
demo-delayed-reservation-sender.workspace = true
test-syscalls.workspace = true

[build-dependencies]
wasm-dep-builder.workspace = true

[features]
default = ['std']
std = [
    "demo-read-big-state/std",
    "demo-proxy/std",
    "demo-reserve-gas/std",
    "demo-delayed-sender/std",
    "demo-constructor/std",
    "demo-waiter/std",
    "demo-init-wait/std",
    "test-syscalls/std",
]
wasm-wrapper = [
    "demo-read-big-state/wasm-wrapper",
    "demo-proxy/wasm-wrapper",
    "demo-reserve-gas/wasm-wrapper",
    "demo-delayed-sender/wasm-wrapper",
    "demo-constructor/wasm-wrapper",
    "demo-waiter/wasm-wrapper",
    "demo-init-wait/wasm-wrapper",
    "test-syscalls/wasm-wrapper",
]
debug = [
    "demo-async-tester/debug",
    "demo-constructor/debug",
    "demo-waiter/debug",
    "demo-delayed-reservation-sender/debug",
    "test-syscalls/debug",
]
