[package]
name = "demo-proxy-reservation-with-gas"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true

[build-dependencies]
wasm-dep-builder.workspace = true

[features]
debug = ["gstd/debug"]
std = ["parity-scale-codec/std", "scale-info/std"]
default = ["std"]
