[package]
name = "gclient-binaries"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
demo-async-tester.workspace = true
demo-calc-hash-in-one-block.workspace = true
demo-custom.workspace = true
demo-constructor = { workspace = true, features = ["std"] }
demo-distributor.workspace = true
demo-mul-by-const.workspace = true
demo-node.workspace = true
demo-program-factory.workspace = true
demo-proxy = { workspace = true, features = ["std"] }
demo-proxy-relay.workspace = true
demo-reserve-gas = { workspace = true, features = ["std"] }

[build-dependencies]
wasm-dep-builder.workspace = true
