[package]
name = "demo-delayed-sender"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.wasm-dep-builder.program]
exclude-features = ["std", "wasm-wrapper"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gstd.workspace = true
io = { package = "demo-delayed-sender-io", path = "io", default-features = false }

[build-dependencies]
wasm-dep-builder.workspace = true

[features]
debug = ["gstd/debug"]
wasm-wrapper = []
std = ["wasm-wrapper"]
default = ["std"]
