[package]
name = "gclient"
description = "API client for Gear node in Rust"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gear-utils.workspace = true
gsdk = { workspace = true, features = ["testing"] }
gear-core.workspace = true
gear-core-errors.workspace = true

futures.workspace = true
anyhow.workspace = true
hex.workspace = true
subxt.workspace = true
parity-scale-codec.workspace = true
thiserror.workspace = true
async-trait.workspace = true
url.workspace = true
wabt.workspace = true
static_assertions.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
wat.workspace = true
env_logger.workspace = true
hex-literal.workspace = true
log.workspace = true
demo-calc-hash.workspace = true
demo-meta-io.workspace = true
demo-new-meta.workspace = true
gmeta = { workspace = true }
gstd = { workspace = true, features = ["debug"] }
demo-wat.workspace = true
gclient-binaries = { path = "binaries" }
