[package]
name = "gclient"
description = "API client for Gear node in Rust"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gear-utils.workspace = true
gsdk = { workspace = true, features = ["testing"] }
gear-core.workspace = true
gear-core-errors.workspace = true

futures.workspace = true
anyhow.workspace = true
hex.workspace = true
subxt.workspace = true
parity-scale-codec.workspace = true
thiserror.workspace = true
async-trait.workspace = true
url.workspace = true
wabt.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
wat.workspace = true
env_logger.workspace = true
hex-literal.workspace = true
log.workspace = true
demo-async-tester.workspace = true
demo-calc-hash.workspace = true
demo-calc-hash-in-one-block.workspace = true
demo-custom.workspace = true
demo-constructor = { workspace = true, features = ["std"] }
demo-distributor.workspace = true
demo-ethereum_light_client = { workspace = true, features = ["serde", "std"] }
demo-meta-io.workspace = true
demo-new-meta.workspace = true
demo-mul-by-const.workspace = true
demo-node.workspace = true
demo-program-factory.workspace = true
demo-proxy = { workspace = true, features = ["std"] }
demo-proxy-relay.workspace = true
demo-reserve-gas = { workspace = true, features = ["std"] }
demo-fungible-token = { workspace = true, features = ["std"] }
ft-io = { path = "../examples/fungible-token/io" }
gmeta = { workspace = true }
gstd = { workspace = true, features = ["debug"] }
demo-wat.workspace = true
demo-bls381 = { workspace = true, features = ["std"] }
ark-serialize = { workspace = true, features = ["derive"] }
ark-scale = { workspace = true, features = ["hazmat"] }
ark-bls12-381 = { workspace = true, features = ["curve"] }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-std = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
reqwest = { version = "0.11.27", features = ["json"] }
eyre = "0.6.12"
serde_json.workspace = true
ssz_rs = { version = "0.9.0" }
futures-util = "0.3.30"
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "e22d9be", features = [
    "consensus",
    "kzg",
    "eips",
    "contract",
    "network",
    "node-bindings",
    "providers",
    "provider-http",
    "provider-ipc",
    "provider-ws",
    "rpc-client",
    "rpc-client-ipc",
    "rpc-client-ws",
    "rpc-types-eth",
    "rpc-types-trace",
    "signers",
    "signer-aws",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
] }
circular-buffer = "0.1.7"
demo-ethereum_bridge = { workspace = true, features = ["std"] }
demo-ethereum_bridge_common = { workspace = true, features = ["std"] }
demo-ethereum_common = { workspace = true, features = ["std"] }
