[package]
name = "demo-ethereum_bridge"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gstd = { workspace = true, features = ["debug"] }
alloy-sol-types = { version = "0.7.4", default-features = false, features = ["json"] }

[build-dependencies]
gear-wasm-builder.workspace = true

[features]
default = ["std"]
std = [
    "alloy-sol-types/std",
]
