[package]
name = "gear-minimal-test-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
const-str.workspace = true
log.workspace = true
parity-scale-codec.workspace = true
scale-info = { workspace = true, features = ["derive"] }

# Frame deps
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true

# Substrate pallet deps
pallet-authorship.workspace = true
pallet-balances.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true

# Primitives
sp-arithmetic.workspace = true
sp-api.workspace = true
sp-authority-discovery.workspace = true
sp-block-builder.workspace = true
sp-core.workspace = true
sp-inherents.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
sp-transaction-pool.workspace = true
sp-version.workspace = true

# Used for the node template's RPCs
frame-system-rpc-runtime-api.workspace = true

# Internal deps
common.workspace = true
gear-core.workspace = true
pallet-gear-messenger.workspace = true
pallet-gear-program.workspace = true
pallet-gear-scheduler.workspace = true
pallet-gear.workspace = true
pallet-gear-bank.workspace = true
pallet-gear-debug.workspace = true
pallet-gear-gas.workspace = true
pallet-gear-rpc-runtime-api.workspace = true
runtime-primitives.workspace = true

[build-dependencies]
substrate-build-script-utils.workspace = true
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"common/std",
	"gear-core/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"runtime-primitives/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-gear/std",
	"pallet-gear-bank/std",
	"pallet-gear-debug/std",
	"pallet-gear-gas/std",
	"pallet-gear-messenger/std",
	"pallet-gear-program/std",
	"pallet-gear-scheduler/std",
	"pallet-gear-rpc-runtime-api/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"runtime-primitives/std",
	"scale-info/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
]
