[package]
name = "wasm-dep-builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cargo_metadata = "0.18.1"
gear-wasm-builder.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
derive_more.workspace = true
fs4 = "0.7"
globset = { version = "0.4.14", features = ["serde1"] }
