[package]
name = "gear-tasks"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc-executor.workspace = true
sc-executor-common.workspace = true
sp-runtime-interface.workspace = true
sp-externalities.workspace = true

futures-executor = "0.3.30"
log.workspace = true

[features]
default = ["std"]
std = []
