[package]
name = "executor-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
codec = { workspace = true, features = ["derive"] }
hex.workspace = true
log.workspace = true
wasm-smith.workspace = true
wasmer.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
wasmprinter.workspace = true
wat.workspace = true
gear-wasm-gen.workspace = true
gear-wasm-instrument.workspace = true
gear-lazy-pages.workspace = true
gear-lazy-pages-common.workspace = true
region.workspace = true
wasmi = { git = "https://github.com/gear-tech/wasmi", branch = "v0.13.2-sign-ext", features = ["virtual_memory"] }
derive_more.workspace = true

## Temporary deps for the reproducing crash script until #2313 is implemented
#clap = { workspace = true, features = ["derive"] }
#
#gear-call-gen.workspace = true
#runtime-primitives.workspace = true
#gear-common.workspace = true
#gear-core.workspace = true
#gear-utils.workspace = true
#vara-runtime = { workspace = true, features = ["std", "dev", "fuzz"] }
#pallet-gear.workspace = true
#pallet-gear-bank.workspace = true
#
#frame-support.workspace = true
#frame-system.workspace = true
#sp-core.workspace = true
#sp-io.workspace = true
#sp-keyring.workspace = true
#sp-runtime.workspace = true
#pallet-balances.workspace = true
#sp-consensus-slots = { workspace = true }
#sp-consensus-babe.workspace = true
#sp-consensus-grandpa.workspace = true
#pallet-im-online.workspace = true
#sp-authority-discovery.workspace = true
#pallet-authorship.workspace = true
