[package]
name = "test-wasm-dep"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
demo-async = { path = "../../examples/async" }
demo-async-init = { path = "../../examples/async-init" }

[build-dependencies]
wasm-dep-builder = { path = "../wasm-dep-builder" }
