[package]
name = "gprimitives-client"
description = "Self-contained client-side primitives"
documentation = "https://docs.rs/gprimitives-client"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = []
