[package]
name = "gprimitives-client"
description = "Self-contained client-side primitives"
documentation = "https://docs.rs/gprimitives-client"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
unroll.workspace = true
num = { workspace = true, features = ["alloc"] }

[dev-dependencies]
rand = { workspace = true, features = ["std", "std_rng"] }

[features]
default = ["std"]
std = []
