[package]
name = "gear-wasm-instrument"
description = "Wasm instrument library for Gear programs"
documentation = "https://docs.rs/gear-wasm-instrument"
keywords = ["gear", "wasm"]
categories = ["wasm"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gwasm-instrument = { workspace = true, features = ["sign_ext"] }
derive_more.workspace = true
enum-iterator.workspace = true

# TODO: remove when tooling is updated
# forcely enable features in transitive dependencies like `gwasm-instrument`
gear-wasm = { version = "0.45.1", default-features = false, features = ["sign_ext", "multi_value"] }

[dev-dependencies]
wasmparser.workspace = true
wat.workspace = true

[features]
default = ["std"]
std = [
    "gwasm-instrument/std",
    "wasmparser/std",
    "gear-wasm/std",
]
