[package]
name = "gear-wasm-instrument"
description = "Wasm instrument library for Gear programs"
documentation = "https://docs.rs/gear-wasm-instrument"
keywords = ["gear", "wasm"]
categories = ["wasm"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gwasm-instrument = { workspace = true, features = ["sign_ext"] }
derive_more.workspace = true
enum-iterator.workspace = true
wasmparser.workspace = true
wasm-encoder = { version = "0.220.0", features = ["wasmparser"] }
bumpalo = "3.16.0"

# TODO: move in a proper place
# parity-wasm
parity-wasm = { workspace = true, features = ["sign_ext", "multi_value"] }
# parity-wasm
gear-wasm = { version = "0.45.1", default-features = false, features = ["sign_ext", "multi_value"] }

[dev-dependencies]
wat.workspace = true
rand.workspace = true
binaryen = "0.12"

[features]
default = ["std"]
std = [
    "gwasm-instrument/std",
    "wasmparser/std",
    "gear-wasm/std",
]
