[package]
name = "demo-reserve-gas"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gstd.workspace = true
io = { package = "demo-reserve-gas-io", path = "io", default-features = false }

[build-dependencies]
wasm-dep-builder.workspace = true

[dev-dependencies]
gtest.workspace = true

[features]
debug = ["gstd/debug"]
wasm-wrapper = []
std = ["wasm-wrapper", "io/std"]
default = ["std"]
