[package]
name = "demo-staking-broker"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gstd.workspace = true
hashbrown.workspace = true
hex.workspace = true
hex-literal.workspace = true
parity-scale-codec.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
gear-core.workspace = true
tokio.workspace = true
gclient.workspace = true
futures.workspace = true
rand.workspace = true
statrs = "0.16"

[build-dependencies]
gear-wasm-builder.workspace = true

[features]
debug = ["gstd/debug"]
std = []
default = ["std"]
