[package]
name = "demo-ethereum_light_client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }
gstd = { workspace = true }
#gstd = { workspace = true, features = ["debug"] }
hex-literal.workspace = true
hex = { workspace = true, optional = true }
ssz_rs = { version = "0.9.0", default-features = false }

[build-dependencies]
gear-wasm-builder.workspace = true

[features]
default = ["std"]
std = ["codec/std", "ssz_rs/std", "serde?/std", "hex?/std"]
serde = ["dep:serde", "hex", "ssz_rs/serde"]
