[package]
name = "demo-wallets"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gstd.workspace = true
parity-scale-codec.workspace = true
demo-wallets-io = { path = "io" }

[build-dependencies]
demo-wallets-io = { path = "io" }
gear-wasm-builder.workspace = true

[dev-dependencies]
gtest.workspace = true

[features]
debug = ["gstd/debug"]
default = ["std"]
std = []
