[package]
name = "demo-init-wait-reply-exit"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gstd.workspace = true

[build-dependencies]
wasm-dep-builder.workspace = true

[features]
debug = ["gstd/debug"]
std = []
default = ["std"]
