[package]
name = "demo-ping-debug"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"
workspace = "../../../"

[lib]

[dependencies]
gstd = { path = "../../../gstd", features = ["debug"] }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
galloc = { path = "../../../galloc", default-features = false }
gcore = { path = "../../../gcore", default-features = false }

[build-dependencies]
gear-wasm-builder = { path = "../../../utils/wasm-builder" }

[features]
std = ["codec/std", "scale-info/std"]
default = ["std"]