[package]
name = "ethexe-txpool"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethexe-common.workspace = true
gprimitives = { workspace = true, features = ["codec"] }

anyhow.workspace = true
hex = { workspace = true, features = ["alloc"] }
parity-scale-codec = { workspace = true, features = ["std", "derive"] }

