[package]
name = "pallet-gear-bridge"
description = "Gear pallet to keep data for bridging"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
primitive-types = { workspace = true, features = ["scale-info"] }
scale-info = { workspace = true, features = ["derive"] }
log.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }

# Internal deps
common.workspace = true
gear-core.workspace = true

# Substrate deps
frame-support.workspace = true
frame-system.workspace = true
frame-benchmarking = { workspace = true, optional = true }
sp-runtime.workspace= true
sp-std.workspace = true
sp-io.workspace = true
binary-merkle-tree.workspace = true
pallet-babe.workspace = true
pallet-session.workspace = true
sp-session.workspace = true
sp-consensus-grandpa.workspace = true

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
env_logger.workspace = true

[features]
default = ['std']
std = [
	"parity-scale-codec/std",
	"primitive-types/std",
	"scale-info/std",
	"log/std",
	"serde/std",
	"common/std",
	"gear-core/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking?/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"binary-merkle-tree/std",
	"pallet-babe/std",
	"pallet-session/std",
	"sp-session/std",
	"sp-consensus-grandpa/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"common/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-session/try-runtime",
]
