[package]
name = "demo-constructor"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.wasm-dep-builder.program]
exclude-features = ["std", "wasm-wrapper"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
gcore.workspace = true
gstd.workspace = true
hex.workspace = true
parity-scale-codec.workspace = true

[build-dependencies]
wasm-dep-builder.workspace = true

[features]
debug = ["gstd/debug"]
wasm-wrapper = []
std = ["wasm-wrapper"]
default = ["std"]
