name: Build

on:
  workflow_call:
    inputs:
      macos:
        type: boolean
        default: false
      win-native:
        type: boolean
        default: true
      release:
        type: boolean
        default: false
      production:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      title:
        type: string
        description: "Pull request title that triggers this workflow."
      number:
        type: string
        description: "Pull request number that triggers this workflow"
      release:
        type: boolean
        default: false
      production:
        type: boolean
        default: false

run-name: ${{ inputs.title }} ( ${{ format('#{0}', inputs.number) }} )

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short
  TERM: xterm-256color
  BINARYEN_VERSION: version_111

jobs:
  dynamic-profiles:
    runs-on: ubuntu-latest
    outputs:
      profiles: ${{ steps.set-matrix.outputs.profiles }}
    steps:
      - id: set-matrix
        run: |
          profiles='{"name": "debug", "flags": ""}'
          if [ "${{ inputs.release }}" = "true" ]; then
            profiles+=', {"name": "release", "flags": "--release"}'
          fi
          profiles="[${profiles}]"
          echo "Profiles: ${profiles}"
          echo "profiles=${profiles}" >> $GITHUB_OUTPUT

  win-native:
    needs: [dynamic-profiles]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build-win-native.yml
    with:
      profiles: ${{ needs.dynamic-profiles.outputs.profiles }}

