name: Test measurements

on:
  schedule:
    - cron: '10 21 * * *'
  workflow_dispatch:

env:
  RUSTUP_HOME: /tmp/rustup_home
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
  COUNT: 100
  BINARYEN_VERSION: version_111

jobs:
  build:
    runs-on: [kuberunner]
    timeout-minutes: 720
    steps:
      - name: "ACTIONS: Checkout"
        uses: actions/checkout@v4

      - name: "Install: Set cargo path"
        run: echo "/tmp/cargo/bin" >> $GITHUB_PATH

      - name: "Install: Rust toolchain"
        uses: dsherret/rust-toolchain-file@v1

      - name: "Show: Versioning"
        run: ./scripts/gear.sh show

      - name: "Install: Build deps"
        run: |
          sudo apt update
          sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler wget bzip2
          sudo wget -c https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN_VERSION/binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz -O - | sudo tar -xz -C .
          sudo cp binaryen-$BINARYEN_VERSION/bin/wasm-opt /usr/bin/

      - name: "Build: Gear"
        run: ./scripts/gear.sh build gear --release --locked --features=runtime-benchmarks

      - name: "Collect: pallet-gear benches"
        run: >-
          ./target/release/gear benchmark pallet --pallet=pallet_gear
          --steps=50
          --repeat=20
          --chain=dev
          --extrinsic=instantiate_module_code_section_per_kb,instantiate_module_data_section_per_kb,instantiate_module_global_section_per_kb,instantiate_module_table_section_per_kb,instantiate_module_type_section_per_kb 
          --heap-pages=4096
          --output ./target/weights.json
          --template ./.maintain/regression-analysis-weight-template.hbs

