name: Upgrade Vara Production

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  
  tag-image:
    runs-on: [self-hosted, sccache, epyc-4, k8s-runner]
    outputs:
      image_tag: ${{ steps.image-tag.outputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create image tag
        id: image-tag
        run: echo "tag=ghcr.io/gear-tech/node-vara:0.1.0-`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
        
  docker:
    runs-on: [self-hosted, sccache, epyc-4, k8s-runner]
    needs: tag-image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Vara-Dockerfile
          push: true
          tags: ghcr.io/gear-tech/node-vara:latest, ${{ needs.tag-image.outputs.image_tag }}
