name: Update production testnet

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  docker:
    runs-on: [self-hosted, sccache, epyc-4, k8s-runner]
    needs: tag-image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Echo tag
        run: echo ${{ needs.tag-image.outputs.image_tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/gear-tech/vara-for-loader:latest
